site_name: Gitlint
site_description: Linting for your git commit messages
site_url: http://jorisroovers.github.io/gitlint/
repo_url: https://github.com/jorisroovers/gitlint
nav:
    - Home: index.md
    - Configuration: configuration.md
    - Rules: rules.md
    - Contrib Rules: contrib_rules.md
    - User Defined Rules: user_defined_rules.md
    - Contributing: contributing.md
    - Changelog: https://github.com/jorisroovers/gitlint/blob/main/CHANGELOG.md

markdown_extensions: [admonition]
theme: 
    name: readthedocs
    navigation_depth: 2
strict: true
extra_css: 
    - extra.css
extra_javascript:
    - extra.js