name: Tests and Checks

# Only run CI on pushes to main and pull requests
# We don't run CI on other branches, but those should be merged into main via a PR anyways which will trigger CI before the merge.
on:
  push:
    branches:
    - main
    - pr-number-base
  pull_request:
    branches:
    - main
    - pr-number-base

concurrency:
  group: ci-${{ github.ref }}-1
  cancel-in-progress: true

jobs:
  # After merging a PR, leave a comment on the PR with a link to the new dev build
  notify:
    if: github.ref == 'refs/heads/pr-number-base'
    runs-on: "ubuntu-latest"
    steps:
      # Checkout code in order to determine PR number
      - uses: actions/checkout@v3.3.0
        with:
          fetch-depth: 0

      - name: Check PR number
        id: pr_check
        run: |
          if [[ -z "${{ github.event.pull_request.number }}" ]]; then
            echo "::error::This workflow requires a pull request to be associated with the push event."
            exit 1
          fi

      - name: Get PR number
        id: pr
        run: |
          pr_number=${{ github.event.pull_request.number }}
          echo "PR_NUMBER2=$pr_number" >> $GITHUB_ENV
          echo "PR_NUMBER2=$pr_number"
  
      - name: Get PR number
        run: |
          commit_sha=$(git rev-parse HEAD)
          pr_number=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/jorisroovers/gitlint/commits/$commit_sha/pulls" | jq -r '.[0].number')
          echo "PR_NUMBER=$pr_number" >> $GITHUB_ENV
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/github-script@v6
        with:
          script: |
            const body = `Build \
            is now available on PyPI!

            Install using:
            \`\`\`sh
            pip install gitlint==
            \`\`\`
            `;
            github.rest.issues.createComment({
              issue_number: process.env.PR_NUMBER,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: body
            });