name: Publish Docker
run-name: "Publish Docker (gitlint_version=${{ inputs.gitlint_version }})"

on:
  workflow_call:
    inputs:
      gitlint_version:
        description: "Gitlint version to build docker image for"
        required: true
        type: string
      push_to_dockerhub:
        description: "Push to dockerhub.com"
        required: false
        type: boolean
        default: false
  workflow_dispatch:
    inputs:
      gitlint_version:
        description: "Gitlint version to build docker image for"
        type: string
      push_to_dockerhub:
        description: "Push to dockerhub.com"
        required: false
        type: boolean
        default: false

jobs:
  publish_docker:
    runs-on: "ubuntu-latest"
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: jorisroovers
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build docker image
        uses: docker/build-push-action@v4
        with:
          build-args: GITLINT_VERSION=${{ inputs.gitlint_version }}
          tags: jorisroovers/gitlint:${{ inputs.gitlint_version }}

      - name: Test docker image
        run: |
          gitlint_version=$(docker run --ulimit nofile=1024 -v $(pwd):/repo \ 
                          jorisroovers/gitlint:${{ inputs.gitlint_version }} --version)
          [ "$(gitlint_version)" == "gitlint, version ${{ inputs.gitlint_version }}" ]

      - name: Push docker image
        uses: docker/build-push-action@v4
        with:
          push: ${{ inputs.push_to_dockerhub }}
          build-args: GITLINT_VERSION=${{ inputs.gitlint_version }}
          tags: jorisroovers/gitlint:${{ inputs.gitlint_version }}