name: Publish Docs

on:
  push:
    branches:
      - main
  
permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0
      - uses: actions/setup-python@v4.6.1
        with:
          python-version: 3.11

      - name: Install Hatch
        run: python -m pip install hatch==1.6.3

      - name: Deploy dev docs
        run: hatch run docs:mike deploy --force --update-aliases dev