name: Test Docker
run-name: "Test Docker (docker_image_tag=${{ inputs.docker_image_tag }}, gitlint_version=${{ inputs.gitlint_version }})"

on:
  workflow_call:
    inputs:
      docker_image_tag:
        description: "Docker tag to pull and run (latest, latest_dev, 0.15.0, etc)"
        required: true
        type: string
        default: "latest"
      gitlint_version:
        description: "Expected gitlint version (0.15.0, etc)"
        required: true
        type: string
        default: "0.15.0"
  workflow_dispatch:
    inputs:
      docker_image_tag:
        description: "Docker tag to pull and run (latest, latest_dev, 0.15.0, etc)"
        required: true
        type: string
        default: "latest"
      gitlint_version:
        description: "Expected gitlint version (0.15.0, etc)"
        required: true
        type: string
        default: "0.15.0"

jobs:
  test-docker:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Run gitlint --version using docker
      run: |
        gitlint_version=$(docker run --ulimit nofile=1024 -v $(pwd):/repo jorisroovers/gitlint:${{ inputs.docker_image_tag }} --version)
        [ "$gitlint_version" == "gitlint, version ${{ inputs.gitlint_version }}" ]